# UI Constants
PROGRESS_DIALOG_MAX_VALUE = 100
PROGRESS_DIALOG_MIN_VALUE = 0
WINDOW_DEFAULT_WIDTH = 1200
WINDOW_DEFAULT_HEIGHT = 800
WINDOW_DEFAULT_X = 100
WINDOW_DEFAULT_Y = 100
LOG_CONSOLE_MAX_HEIGHT = 200

# Progress Constants
PROGRESS_MAX = 100
PROGRESS_MIN = 0
PROGRESS_COMPLETE = 100
PROGRESS_WEIGHT_DOWNLOAD = 0.8
PERCENTAGE_MULTIPLIER = 100
DEFAULT_PERCENTAGE_MULTIPLIER = 100

# File Size Constants
MAX_FILE_SIZE_KB = 512
MAX_FILENAME_LENGTH = 255
MAX_DESCRIPTION_LENGTH = 150
MAX_ERROR_MESSAGE_LENGTH = 100
MAX_CONTENT_SIZE = 1024 * 1024  # 1MB

# HTTP Constants
HTTP_TIMEOUT_SHORT = 10
HTTP_TIMEOUT_LONG = 30
OLLAMA_BASE_URL = "http://localhost:11434"
CACHE_EXPIRY_SECONDS = 3600
DEFAULT_USER_AGENT = "AI-Coder-Assistant/2.0"

# Model Constants
DEFAULT_MODEL_NAME = "claude-3-sonnet-20240229"
DEFAULT_MODEL_VERSION = "20240229"

# Web Scraping Constants
DEFAULT_MAX_PAGES = 15
DEFAULT_MAX_DEPTH = 4
DEFAULT_LINKS_PER_PAGE = 50
DEFAULT_MAX_WORKERS = 6

# Timeout Constants
WAIT_TIMEOUT_MS = 5000
GRACEFUL_SHUTDOWN_WAIT = 5
GRACEFUL_SHUTDOWN_WAIT_MS = 5000

# Color Constants
DEFAULT_SEVERITY_COLOR = '888888'
DEFAULT_TEXT_COLOR = '495057'
DEFAULT_FONT_WEIGHT = 500

# Security Constants
SSL_VERIFY_DEFAULT = True
VERIFY_DEFAULT = True 