# UI Constants
PROGRESS_DIALOG_MAX_VALUE = 100
PROGRESS_DIALOG_MIN_VALUE = 0
WINDOW_DEFAULT_WIDTH = 1200
WINDOW_DEFAULT_HEIGHT = 800
WINDOW_DEFAULT_X = 100
WINDOW_DEFAULT_Y = 100
LOG_CONSOLE_MAX_HEIGHT = 200

# Progress Constants
PROGRESS_MAX = 100
PROGRESS_MIN = 0
PROGRESS_COMPLETE = 100
PROGRESS_WEIGHT_DOWNLOAD = 0.8
PERCENTAGE_MULTIPLIER = 100
DEFAULT_PERCENTAGE_MULTIPLIER = 100

# File Size Constants
MAX_FILE_SIZE_KB = 512
MAX_FILENAME_LENGTH = 255
MAX_DESCRIPTION_LENGTH = 150
MAX_ERROR_MESSAGE_LENGTH = 100
MAX_CONTENT_SIZE = 1024 * 1024  # 1MB

# HTTP Constants
HTTP_TIMEOUT_SHORT = 10
HTTP_TIMEOUT_LONG = 30
OLLAMA_BASE_URL = "http://localhost:11434"
CACHE_EXPIRY_SECONDS = 3600
DEFAULT_USER_AGENT = "AI-Coder-Assistant/2.0"

# Model Constants
DEFAULT_MODEL_NAME = "claude-3-sonnet-20240229"
DEFAULT_MODEL_VERSION = "20240229"

# Web Scraping Constants
DEFAULT_MAX_PAGES = 15
DEFAULT_MAX_DEPTH = 4
DEFAULT_LINKS_PER_PAGE = 50
DEFAULT_MAX_WORKERS = 6

# Timeout Constants
WAIT_TIMEOUT_MS = 5000
GRACEFUL_SHUTDOWN_WAIT = 5
GRACEFUL_SHUTDOWN_WAIT_MS = 5000

# Color Constants
DEFAULT_SEVERITY_COLOR = "888888"
DEFAULT_TEXT_COLOR = "495057"
DEFAULT_FONT_WEIGHT = 500

# Security Constants
SSL_VERIFY_DEFAULT = True
VERIFY_DEFAULT = True

# Performance Metrics Constants
CPU_HIGH_THRESHOLD = 80
CPU_MEDIUM_THRESHOLD = 60
MEMORY_HIGH_THRESHOLD = 85
MEMORY_MEDIUM_THRESHOLD = 70
METRICS_UPDATE_INTERVAL_MS = 2000

# UI Layout Constants
CHAT_AREA_MAX_HEIGHT = 300
DEFAULT_FONT_SIZE = 12
LARGE_FONT_SIZE = 14
BOLD_FONT_WEIGHT = 700
NORMAL_FONT_WEIGHT = 400

# Table Constants
DEFAULT_TABLE_COLUMNS = 4
DEFAULT_TABLE_ROW_HEIGHT = 25
DEFAULT_TABLE_HEADER_HEIGHT = 30

# Dialog Constants
DEFAULT_DIALOG_WIDTH = 400
DEFAULT_DIALOG_HEIGHT = 300
CONFIG_DIALOG_WIDTH = 500
CONFIG_DIALOG_HEIGHT = 400

# File Dialog Constants
DEFAULT_FILE_FILTER = "All Files (*.*)"
PYTHON_FILE_FILTER = "Python Files (*.py)"
JSON_FILE_FILTER = "JSON Files (*.json)"
TEXT_FILE_FILTER = "Text Files (*.txt)"

# API Constants
DEFAULT_API_PORT = 8000
DEFAULT_API_HOST = "0.0.0.0"
API_DOCS_PATH = "/docs"
API_HEALTH_PATH = "/health"

# Docker Constants
DEFAULT_DOCKER_TAG = "ai-coder-app:latest"
DEFAULT_DOCKER_TIMEOUT = 300

# Threading Constants
DEFAULT_THREAD_POOL_SIZE = 4
MAX_THREAD_POOL_SIZE = 10
WORKER_TIMEOUT_SECONDS = 300

# Logging Constants
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_FILE_MAX_SIZE = 10 * 1024 * 1024  # 10MB
LOG_FILE_BACKUP_COUNT = 5

# Database Constants
DEFAULT_DB_TIMEOUT = 30
DEFAULT_DB_MAX_CONNECTIONS = 10
DEFAULT_DB_POOL_SIZE = 5

# Cache Constants
DEFAULT_CACHE_SIZE = 1000
DEFAULT_CACHE_TTL = 3600
MODEL_CACHE_TTL = 86400  # 24 hours

# Validation Constants
MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 128
MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH = 50
MAX_EMAIL_LENGTH = 254

# Rate Limiting Constants
DEFAULT_RATE_LIMIT = 100
DEFAULT_RATE_LIMIT_WINDOW = 3600  # 1 hour
API_RATE_LIMIT = 1000
API_RATE_LIMIT_WINDOW = 3600

# Error Constants
MAX_ERROR_RETRIES = 3
ERROR_RETRY_DELAY = 1

# Notification Constants
DEFAULT_NOTIFICATION_TIMEOUT = 5000
SUCCESS_NOTIFICATION_TIMEOUT = 3000
ERROR_NOTIFICATION_TIMEOUT = 10000

# Search Constants
DEFAULT_SEARCH_LIMIT = 50
MAX_SEARCH_LIMIT = 1000
DEFAULT_SEARCH_TIMEOUT = 30

# Export Constants
DEFAULT_EXPORT_FORMAT = "json"
SUPPORTED_EXPORT_FORMATS = ["json", "csv", "xml", "yaml"]
MAX_EXPORT_SIZE = 100 * 1024 * 1024  # 100MB

# Import Constants
MAX_IMPORT_FILE_SIZE = 50 * 1024 * 1024  # 50MB
SUPPORTED_IMPORT_FORMATS = ["json", "csv", "xml", "yaml", "zip"]

# Backup Constants
DEFAULT_BACKUP_RETENTION_DAYS = 30
MAX_BACKUP_SIZE = 1024 * 1024 * 1024  # 1GB
BACKUP_COMPRESSION_LEVEL = 6
